### ISSUE TITLE
Untracked files don't show in tig, but do in "git status"

### ISSUE THREAD

**Issue by joehoyle** [jonas/tig#456] opened 2015-11-17 00:19 UTC
I'm not sure if I'm using something wrong, but quite often new files I create don't show under "Untracked files" in the `tig` status view, whereas they do when running `git status`:

Tig:

![](https://s3.amazonaws.com/joehoyle-captured/XywqE.png)

Git status:

![](https://s3.amazonaws.com/joehoyle-captured/kzKDg.png)

**Comment by jonas** [comment] 2016-01-05 01:44
What version of Git are you using?

**Comment by netei** [comment] 2016-01-05 08:06
Does it work if you restart tig ? If yes, you probably got out of date (try refreshing with `R`)

**Comment by joehoyle** [comment] 2016-01-06 23:49
Restarting does not fix it, it's definitely not refresh based, the files never show up.

Git version: git version 2.5.4 (Apple Git-61)

**Comment by h3xx** [comment] 2016-01-15 15:24
>Git version: git version 2.5.4 (Apple Git-61)

Can you replicate it using a newer version of git (current is 2.7.0).

**Comment by joehoyle** [comment] 2016-01-17 16:22
I upgraded to `git version 2.7.0` but this didn't improve things,

git status:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.tags
	content/db.php
	content/plugins-mu/hm-rewrite/
	content/plugins-mu/hm-stack-api/inc/endpoints/class-pull-requests-endpoint.php
	content/plugins-mu/hm-stack-core/inc/application/class-application-mock.php
	content/plugins-mu/hm-stack-core/inc/application/class-application.php.orig
	content/plugins-mu/hm-stack-core/inc/application/ssl.php
	content/plugins-mu/hm-stack-service-report/
	content/plugins-mu/hm-stack-users/
	logfile
```

Tig:

```
Untracked files:
  (no files)
```

**Comment by djromero** [comment] 2016-01-27 16:45
I had a similar issue. In my case the problem was a renamed submodule.
Whe I ran: 
```
git ls-files  --others  --exclude-standard
```
It failed with exit status 128 and a very helpful error message: **fatal: Not a git repository: /path/to/offending/directory/../path/to/not/existing/submodule**

I removed the directory causing the problems (previously a git submodule) and it worked fine again.

I suggest including the output of `git ls-files` in the terminal when the command fails.

**Comment by konradrr** [comment] 2017-06-23 13:50
I had the same issue for `tig 2.2.2` on `macOS 10.12`. In my case, the following operations helped:
```
brew remove tig
rm /usr/local/etc/tigrc
brew install tig
```

Probably there were some deprecates in `tigrc`.

**Comment by jonas** [comment] 2017-06-23 14:03
This looks similar to #407 for which a fix (https://github.com/Homebrew/legacy-homebrew/issues/44055) was submitted in now legacy brew to no longer install tigrc since subsequent upgrades would not update the file.

The fix is indeed to remove the tigrc in /usr/local so Tig uses the default configuration which is compiled into the binary.

**Closed by jonas** 2017-06-23 14:03 UTC
Labels: Status and staging

**Comment by jonas** [comment] 2017-06-23 14:06
Closing this as it is quite old and there has been a few changes to the settings. Please open a new issue if the problem can be reproduced with the newest version.
