### ISSUE TITLE
Tig does not maximize after search

### ISSUE THREAD

**Issue by Perlence** [jonas/tig#845] opened 2018-06-27 19:41 UTC
Tig stops resizing correctly after search. Here's a video https://youtu.be/001uQ35RYKI
I built tig on Debian 9.4. It happened to me both on `TERM=xterm-256color` and `TERM=tmux-256color`. Apparently this started happening after f21329ee4c69e20e76f4ffb2766b84a770644452.

**Comment by koutcher** [comment] 2018-06-28 20:35
The problem is not actually linked to the search function (any command you type will cause the same issue) but to the use of readline. This can be confirmed by using --without-readline option when compiling tig.

It is quite annoying but it looks like it won't be easy to solve: http://invisible-island.net/ncurses/ncurses.faq.html#readline_library

**Comment by Perlence** [comment] 2018-06-28 21:11
Thank you for investigating! Hm, running `./configure --without-readline` still leaves readline in config.h, so I had to comment it out manually. Well, I personally can live without readline, since the bug is much more annoying than being unable to use search history.

**Comment by koutcher** [comment] 2018-06-28 21:46
--without-readline works ok on macOS but is broken on Linux. You also have to remove readline from config.make to avoid linking with libreadline.so

**Comment by Perlence** [comment] 2018-06-29 09:35
Thanks, it's good to know!

**Comment by jonas** [comment] 2018-07-08 00:14
Fixed in #846

**Closed by jonas** 2018-07-08 00:14 UTC

**Comment by Perlence** [comment] 2018-07-08 09:09
Good job y'all, thanks!
