### ISSUE TITLE
If very many commits, It’s so slowly. I think it's a problem.

### ISSUE THREAD

**Issue by sachin21** [jonas/tig#366] opened 2015-01-25 12:47 UTC
I can’t write C language :-(
Please fix it.

**Comment by edi9999** [comment] 2015-01-26 16:28
I have a repository with 8100 commits, and I don't experience any issues. Is your repository open source ? Maybe it has a lot of raw data. Does git work fast on the repository ?

**Comment by vivien** [comment] 2015-01-26 16:39
A good example is the linux tree. Since a few commits (didn't bisect yet), tig takes about 6 seconds to show something on screen. Then if you play with rows (keep down pressed, then up), you'll note a big lag. All of it is related to commits loading. Once the interface shows up, stop loading the main view (with 'z' by default) makes tig responsive again. The lag could be fixed with a max-loading option, set to e.g. 10000 by default, but the startup issue is annoying.

**Comment by jonas** [comment] 2015-01-27 03:45
So this is basically #324.

**Comment by jonas** [comment] 2015-01-27 03:46
See https://github.com/jonas/tig/issues/310#issuecomment-57972302 for workarounds until I get around to fixing this and releasing 2.1.

**Comment by sachin21** [comment] 2015-01-29 06:08
@jonas oh! I see!
Thank you! :)

**Comment by sachin21** [comment] 2015-01-29 06:10
@edi9999 I have a 40000 commits private repository on company.

**Comment by jonas** [comment] 2015-02-07 04:25
@sachin21 I will close this since issue is a duplicate of the problems discussed in #310 and #324. Part of #368 has been implemented so that you can now limit the number of commits loaded in the main view by default, see [contrib/large-repo.tigrc](https://github.com/jonas/tig/blob/master/contrib/large-repo.tigrc) for useful settings and feel free to suggest improvements.

**Closed by jonas** 2015-02-07 04:25 UTC
