### ISSUE TITLE
How to apply `git diff --color-words HEAD | less -r` in tig diff window

### ISSUE THREAD

**Issue by avatar-lavventura** [jonas/tig#1117] opened 2021-06-12 14:36 UTC
In `diff` window; if possible I want to apply `git diff --color-words HEAD | less -r``  instead of `git diff`, how can I achieve it?

The difference could be seens as below, where only the added character shown:

On linux terminal: `$ git diff --ignore-blank-lines --color-words HEAD | less -r`
<img width="670" alt="diff --git abrokerDriver py bbrokerDriver py" src="https://user-images.githubusercontent.com/18537398/121779432-435a5280-cba4-11eb-9075-bcfc690ac083.png">

On `tig`:

<img width="651" alt="1 file changed, 1 insertion(+), 1 deletion(-)" src="https://user-images.githubusercontent.com/18537398/121779438-4b19f700-cba4-11eb-9ba7-28d01feea8ed.png">

--------

I have tried `TIG_DIFF_OPTS="--ignore-blank-lines --color-words" tig`, or `TIG_DIFF_OPTS='--ignore-blank-lines --color-words' tig --word-diff=plain`, which did not work properly. Example output:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/18537398/121783835-925eb280-cbb9-11eb-9b32-2fa699d17813.png">

-------------

I think this issue is considered as feature (https://github.com/jonas/tig/issues/47) and still in progress.

**Comment by krobelus** [comment] 2021-06-14 17:04
Duplicate of #47

**Closed** 2022-05-15 07:26 UTC

**Comment by avatar-lavventura** [comment] 2022-05-15 10:11
It is a duplicated issue since 2012, seems like it is abandoned.

**Comment by koutcher** [comment] 2022-05-18 18:22
There might be hope with #1140.

**Comment by avatar-lavventura** [comment] 2022-05-18 18:27
@koutcher Looking forward to seeing this awesome merge, thanks
