### ISSUE TITLE
Detached head is not shown in tig --all

### ISSUE THREAD

**Issue by petersohn** [jonas/tig#511] opened 2016-07-14 08:13 UTC
To reproduce the bug, do the following:
```
git init
touch a
git add .
git commit -a -m 'Initial commit'
echo a>>a
git commit -a -m 'Branch1'
git reset --hard HEAD~1
echo b>>a
git commit -a -m 'Branch2'
git checkout 'HEAD@{2}'
tig --all
```

Here, tig shows only the initial commit and the master (now `Branch2`), but does not show the HEAD (`Branch1`). However, `git log --all`shows all commits.

`tig log` has the same issue.

**Comment by jonas** [comment] 2016-08-07 02:22
I am not able to reproduce this.

With `tig --all`:
```
2016-08-06 22:17 Jonas Fonseca o [master] Branch2
2016-08-06 22:17 Jonas Fonseca │ o [HEAD] Branch1
2016-08-06 22:17 Jonas Fonseca I─┘ Initial commit
```

With `git log --graph --all  --decorate`:
```
* commit 189b577daaea98e4000c7686b77497beebbc9a39 (master)
| Author: Jonas Fonseca <jonas.fonseca@gmail.com>
| Date:   Sat Aug 6 22:17:34 2016 -0400
|
|     Branch2
|
| * commit 0f7ea8d3b44aa46161ed17cecb1ca1cc2a389394 (HEAD)
|/  Author: Jonas Fonseca <jonas.fonseca@gmail.com>
|   Date:   Sat Aug 6 22:17:34 2016 -0400
|
|       Branch1
|
* commit ba69f03ecf81b7317eb3a6b726729e7c4b9c0225
  Author: Jonas Fonseca <jonas.fonseca@gmail.com>
  Date:   Sat Aug 6 22:17:34 2016 -0400

      Initial commit
```

and with `tig log --all`:
```
commit 189b577daaea98e4000c7686b77497beebbc9a39
Refs: [master]
Author: Jonas Fonseca <jonas.fonseca@gmail.com>
Date:   Sat Aug 6 22:17:34 2016 -0400

    Branch2

 a | 1 +
 1 file changed, 1 insertion(+)

commit 0f7ea8d3b44aa46161ed17cecb1ca1cc2a389394
Refs: [HEAD]
Author: Jonas Fonseca <jonas.fonseca@gmail.com>
Date:   Sat Aug 6 22:17:34 2016 -0400

    Branch1

 a | 1 +
 1 file changed, 1 insertion(+)

commit ba69f03ecf81b7317eb3a6b726729e7c4b9c0225
Author: Jonas Fonseca <jonas.fonseca@gmail.com>
Date:   Sat Aug 6 22:17:34 2016 -0400

    Initial commit

 a | 4 ++++
 1 file changed, 4 insertions(+)
```

**Comment by petersohn** [comment] 2016-08-08 10:43
It seems to work on latest master. I could reproduce it on the latest release (2.1.1).

**Comment by jonas** [comment] 2016-08-08 12:20
Thanks for validating. I'll go ahead and close this then.

**Closed by jonas** 2016-08-08 12:20 UTC
Labels: More info needed
