### ISSUE TITLE
Use inotify/fswatch for file changes

### ISSUE THREAD

**Issue by MasseGuillaume** [jonas/tig#695] opened 2017-07-28 11:52 UTC
For example, on the status view, I need to press F5 to update the view. A file watch on the directory removing gitignore entries could notify tig to update.

**Comment by jonas** [comment] 2017-07-28 13:05
Hi Guillaume, fswatch indeed looks like the best option for such a feature.

I will go ahead and close this as a duplicate of #301 which has a few comments about how the current "watch" mechanism is implemented.

**Closed by jonas** 2017-07-28 13:05 UTC
